### PR TITLE
GetSerializedStateForRun Pagination

### PR DESCRIPTION
**Pull request by ryanbrainard**
`GetSerializedStateForRun` does not support pagination of history, so if a state marker is not found on the first page, it returns an error. This changes the function to use `GetWorkflowExecutionHistoryPages` to page through history until the state marker is found, and only then returns an error if it is not found.

### CODE REVIEW

**Review by amerine — APPROVED** [review]
Looks good today me. Travis has an odd error I can’t diagnose from my phone.

**Comment by ryanbrainard** [comment]
> Travis has an odd error I can’t diagnose from my phone.

I'm fixing error on another branch and will rebase this. It's weird stuff from the Go version being so old.

**Comment by ryanbrainard** [comment]
@amerine this fixes the Travis errors: https://github.com/sclasen/swfsm/pull/203

**Comment by ryanbrainard** [comment]
I rebased on top of #203 and changed the base of this PR to that branch to maintain a clean diff here.

**Pull request merged**
