### PR TITLE
add and use a Mutable log.Logger so that it can be modified

### PR DESCRIPTION
**Pull request by sclasen**
by those that desire to do so

for #68  @uberbrodt  does this solve the issue?

```go
import "log"
import swflog "github.com/sclasen/swfsm/log"

swflog.Log = log.New(...)
```

### CODE REVIEW

**Comment by uberbrodt** [comment]
@sclasen This looks good. Let me test it and I'll get back to you. Thanks!

**Comment by uberbrodt** [comment]
@sclasen Sorry it took so long to look into this. There's a modification I submitted in #86. Let me know if that makes sense?

**Comment by sclasen** [comment]
@uberbrodt sorry about the delays here!

**Comment by uberbrodt** [comment]
@sclasen No worries. Thanks!

**Pull request merged**
