### PR TITLE
Add FailWorkflow convenience method to FSMContext

### LINKED ISSUE #155: Create an FSMContext.FailWorkflow() convenience method
FSMContext already has a very similar method `CancelWorkflow`.  

I could send a PR, just wasn't sure what state the FSM should transition to.  Should I add a new constant for `FailedState` similar to `CanceledState` and transition to that?

### PR DESCRIPTION
**Pull request by ryanwalls**
Move FSMContext into separate file instead of keeping in fsm_models.

Closes #155

### CODE REVIEW

**Comment by ryanwalls** [comment]
Thoughts on having FSMContext in its own file?  Seems like it's big enough/complicated enough to warrant a separate file.  Makes the tests easier to read.

**Comment by sclasen** [comment]
FSMContext as its own file seems fine.

I think you are going to need to add a `failedState *FSMState` field to FSM,  `FSM.AddFailedState(...)` and `FSM.DefaultFailedState()` funcs, and set the default in `FSM.Init` if unset.   

Following the same pattern as `errorState`, `FSM.AddErrorState`, `FSM.DefaultErrorState()` and  `FSM.Init`

**Comment by ryanwalls** [comment]
Ah, good catch.  Fixed.

**Comment by ryanwalls** [comment]
Yeah, I'm good with that naming convention.  Updated.

**Comment by sclasen** [comment]
:+1:

**Pull request merged**
