### PR TITLE
Auto register interest

### PR DESCRIPTION
**Pull request by ryanbrainard**
Replace `RegisterXInterest` methods with auto-registration internal to the `TestListener`. This means that tests can just call the `AwaitX[For]` methods without having to pre-register interest for a given workflow id. All workflow ids are now recorded automatically, so there is a small risk of overrunning the channels, but in that case, the listener will not block and fail fast. If we need more capacity, `interestChannelSize` can always be increased, but 1000 was used before and even with explicit registration and didn't cause any known problems.

### CODE REVIEW

**Comment by sclasen** [comment]
:+1:

**Comment by danp** [comment]
Forgive me since it's been a while since I've been into this stuff, but:

I thought calling RegisterXInterest in advance was required because otherwise there's a race between when you do something and when you wait to see if it happened. For example, if this happens:

1. do something that makes the workflow react
2. event X happens
3. your Await code runs, waiting for event X, but it's already happened

Am I forgetting that events are always captured and this shakes out some other way?

**Comment by danp** [comment]
I guess since the forwarder calls [eg getHistoryInterest](https://github.com/sclasen/swfsm/blob/a86abdcae755064de6ed79f0591270f161dd0a0f/testing/listener.go#L312) that channels for all workflows will be created?

**Comment by ryanbrainard** [comment]
Yes, that's correct. The change is to automatically create the channel (i.e. register interest) if it does not exist. Before, this was an explicit step, and could result in the race you mentioned, but this automatically does its in Step 2, so it will be waiting for you in Step 3. This uses more memory because it's recording all the workflows (although most tests are still only running one at a time), but is less to think about for the programmer.

**Comment by danp** [comment]
👍 Thanks!

**Pull request merged**
