### PR TITLE
Serializer supporting jsonpb

### PR DESCRIPTION
**Pull request by lstoll**
This PR adds a `jsonpbserializer`, which is an implementation of `StateSerializer`. This implementation will serialize types implementing `proto.Message` using the [jsonpb](https://github.com/golang/protobuf/tree/master/jsonpb) serializer. This will serialize them using a [defined mapping)(https://developers.google.com/protocol-buffers/docs/proto3#json). This has the benefit of generating better output for protobuf types like Timestamps, and also is consistent across other languages generating json from these types.

This serializer supports a fallback serializer for types that don't implement this, which defaults to the standard JSON serializer.

### CODE REVIEW

**Comment by lstoll** [comment]
fwiw I also dropped the vendored protobufs, and replaced it with a `go get ./...`. As a lib I don't think we can really prescribe versions of deps in go.

**Comment by sclasen** [comment]
👍

**Comment by lstoll** [comment]
I can't merge 🙃

**Comment by sclasen** [comment]
oops!, invited you, merging

**Pull request merged**
