### PR TITLE
store all inputs and controls in the correlator

### PR DESCRIPTION
**Pull request by sclasen**
rather than doing #50 I think we should just always store the inputs.

We should teach the FSM to stripe data and correlator serializations across multiple serializations/markers instead of making this harder to use when you need it.

### CODE REVIEW

**Comment by ryanwalls** [comment]
:+1: 

Like the change.

**Comment by ryanwalls** [comment]
Any concerns about merging this?  Would love to get this change as it would clean up my code considerably. :)

**Comment by sclasen** [comment]
@ryanwalls quite close to merging this, can you just use the branch in the meantime?  I can rebase it if there are other changes.

This will get merged as is for sure.  We are just doing some testing of the recent S3Serializer stuff with this.

If we just blindly merge this there is a decent possibility that we can break things, in the case of FSMs that start lots of children/activites, etc.  With the new data in the correlator, its serialized representation can easily go bigger than the 32K limit on markers, which is why this stuff wasn't in there originally.

So, just making sure the S3Serializer works correctly as the fsm SystemSerializer that works with State and Correlator

**Comment by ryanwalls** [comment]
@sclasen no worries.  I can either use the branch or wait until you merge.  Just checking in case it was something that just had been deprioritized.

**Comment by sclasen** [comment]
bringing this in

**Comment by ryanwalls** [comment]
+1

**Pull request merged**
