### PR TITLE
vendor jsonb

### PR DESCRIPTION
**Pull request by sclasen**
/cc @ryanwalls I think this is why your build was failing, can you pull this down and see if `make install` works?

### CODE REVIEW

**Comment by lstoll** [comment]
I intentionally avoided this because go doesn't handle nested dependencies like this. Because this is a library and how go handles vendoring, there's no way for us to force a particular version of something on the end user unless we re-write imports. So anything vendored here will be used when developing this library, but not necessarily when it's consumed which could cause issues.

So I left it out, so CI running `go get ./...` will fetch the latest version of our dependencies and maybe act as a canary when we need to update things.

To be honest though, I'm not sure what the flavor of the week is in the go community though for this problem.

**Comment by sclasen** [comment]
aha gotcha, wont merge then

**Comment by lstoll** [comment]
We do already have `vendor/` stuff, so I guess we should either add this, or drop `vendor/` altogether.

Maybe @freeformz can give some tips on how best to manage "dependencies within dependencies"?

**Comment by freeformz** [comment]
Most tools flatten out dependencies transitively. So the vendored deps would be pulled up to the importer of swfsm. Each tool handles the lock files of dependencies differently though. Most don't really bother using the info at all. For a real solution you'll have to wait until go1.8 or maybe later. 

Generally speaking I suggest locking/vendoring your deps for the ease of testing and to provide a reference point wrt versions are being tested against.

**Comment by lstoll** [comment]
Fair call, landing this one now then 👍

**Comment by ryanwalls** [comment]
See my comment https://github.com/sclasen/swfsm/issues/186#issuecomment-246787720.  I recommend Glide.  It even has a `--strip-vendor` flag which allows me to actually handle the case where a library checks in their vendor folder (like this one. :) ).

**Comment by freeformz** [comment]
glide also works. govendor strips deps `vendor` directories automatically. As does godep. Not sure about many of the other tools.

**Pull request merged**
