### PR TITLE
zero out registered pollers when StopPollers finishes

### LINKED ISSUE #122: Feature request: Make `StopPollers` idempotent
Currently, if you call it a second time without `Register`ing any new pollers, `StopPollers` blocks indefinitely.

### PR DESCRIPTION
**Pull request by sclasen**
should fix #122

### CODE REVIEW

**Comment by ryanwalls** [comment]
:+1:

**Comment by dpiddy** [comment]
Does this need mutex protection?

**Comment by sclasen** [comment]
Has it no?

**Comment by dpiddy** [comment]
Indeed it does, please disregard. Should not try to comment from my phone.

**Comment by sclasen** [comment]
:smile:

**Pull request merged**
