### PR TITLE
Test server

### PR DESCRIPTION
**Pull request by sclasen**
Start an httptest server on localhost, and configure an swf.SWF that points at it.

@fabiokung @dgouldin  do you see such a thing being valuable? Or would it be death by boilerplate to mock out parts of SWF?

### CODE REVIEW

**Comment by dgouldin** [comment]
Seems like a pretty daunting task to me.

**Comment by sclasen** [comment]
Yeah, if you mean writing a full impl, for sure, but here more to provide a
way to easily write a test server that responds to poll for activity task,
etc, on a one off basis

Maybe mocking the client is easier though

**Comment by fabiokung** [comment]
no strong opinions on this one, but I guess +1 on mocking the client. I can only see this being useful on multi-language scenarios.

**Comment by sclasen** [comment]
closing

**Pull request closed without merging**
